apiVersion: apps/v1
kind: Deployment

metadata:
  name: hello-app
  namespace: cicd

spec:
  replicas: 2

  selector:
    matchLabels:
      app: hello-app

  template:
    metadata:
      labels:
        app: hello-app

    spec:
      containers:
      - name: hello-app
        image: leonardoq/hello-app:5d18e54
        ports:
        - containerPort: 5000
